// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3qQ9Vnije6MXfUvDcLdzg_OVUXG8nR74',
    appId: '1:866423970277:web:ef18068762d143e1eff70c',
    messagingSenderId: '866423970277',
    projectId: 'chatapp-ef5bd',
    authDomain: 'chatapp-ef5bd.firebaseapp.com',
    storageBucket: 'chatapp-ef5bd.appspot.com',
    measurementId: 'G-K99FK2L0QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9i6_JRGqbattEoi-AphoBe1IfzrM6RZ4',
    appId: '1:866423970277:android:4d541f27ef9f06ffeff70c',
    messagingSenderId: '866423970277',
    projectId: 'chatapp-ef5bd',
    storageBucket: 'chatapp-ef5bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrySPq0TvAiTXCHdgcybXH9hyGin4p1CQ',
    appId: '1:866423970277:ios:7d36c79eb9b8f2a7eff70c',
    messagingSenderId: '866423970277',
    projectId: 'chatapp-ef5bd',
    storageBucket: 'chatapp-ef5bd.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
